package com.roleta.app.ui.theme

import androidx.compose.ui.graphics.Color

// Warm amber brand palette (Material 3 tonal roles).

// ── Light ─────────────────────────────────────────────────────────────────────
val LightPrimary = Color(0xFF8B5000)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDDB3)
val LightOnPrimaryContainer = Color(0xFF2C1600)
val LightSecondary = Color(0xFF725B42)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFEDEBC)
val LightOnSecondaryContainer = Color(0xFF291806)
val LightTertiary = Color(0xFF5A6135)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDFE7AE)
val LightOnTertiaryContainer = Color(0xFF1D2000)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurface = Color(0xFFFFF8F4)
val LightOnSurface = Color(0xFF201B16)
val LightSurfaceVariant = Color(0xFFF2DFD1)
val LightOnSurfaceVariant = Color(0xFF51453A)
val LightOutline = Color(0xFF837468)
val LightOutlineVariant = Color(0xFFD5C3B5)
val LightSurfaceDim = Color(0xFFE3D8D1)
val LightSurfaceBright = Color(0xFFFFF8F4)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFCF2EB)
val LightSurfaceContainer = Color(0xFFF6ECE5)
val LightSurfaceContainerHigh = Color(0xFFF0E6DF)
val LightSurfaceContainerHighest = Color(0xFFEBE0D9)
val LightInverseSurface = Color(0xFF362F2A)
val LightInverseOnSurface = Color(0xFFF9EFE7)
val LightInversePrimary = Color(0xFFFFB951)

// ── Dark ──────────────────────────────────────────────────────────────────────
val DarkPrimary = Color(0xFFFFB951)
val DarkOnPrimary = Color(0xFF4A2800)
val DarkPrimaryContainer = Color(0xFF693C00)
val DarkOnPrimaryContainer = Color(0xFFFFDDB3)
val DarkSecondary = Color(0xFFE1C1A4)
val DarkOnSecondary = Color(0xFF402C18)
val DarkSecondaryContainer = Color(0xFF59422C)
val DarkOnSecondaryContainer = Color(0xFFFEDEBC)
val DarkTertiary = Color(0xFFC4CB81)
val DarkOnTertiary = Color(0xFF2E3408)
val DarkTertiaryContainer = Color(0xFF43491D)
val DarkOnTertiaryContainer = Color(0xFFDFE7AE)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurface = Color(0xFF18120D)
val DarkOnSurface = Color(0xFFEDE0D7)
val DarkSurfaceVariant = Color(0xFF51453A)
val DarkOnSurfaceVariant = Color(0xFFD5C3B5)
val DarkOutline = Color(0xFF9E8E81)
val DarkOutlineVariant = Color(0xFF51453A)
val DarkSurfaceDim = Color(0xFF18120D)
val DarkSurfaceBright = Color(0xFF3F3832)
val DarkSurfaceContainerLowest = Color(0xFF120D08)
val DarkSurfaceContainerLow = Color(0xFF201B16)
val DarkSurfaceContainer = Color(0xFF251F1A)
val DarkSurfaceContainerHigh = Color(0xFF302924)
val DarkSurfaceContainerHighest = Color(0xFF3B342E)
val DarkInverseSurface = Color(0xFFEDE0D7)
val DarkInverseOnSurface = Color(0xFF362F2A)
val DarkInversePrimary = Color(0xFF8B5000)
