# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a larger heap size helps prevent OutOfMemoryErrors during build.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects.
# org.gradle.parallel=true

# Enables the Gradle build cache.
org.gradle.caching=true

# Kotlin code style for this project: "official" or "android"
kotlin.code.style=official

# AndroidX libraries use this property to enable/disable Jetifier
android.useAndroidX=true
